#!/usr/bin/env python3
from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
UNIT_DIR = ROOT / "data" / "generated_units" / "algoritmos-estructuras-datos"

WEEKS = {1:[1,2],2:[3,4,5],3:[6,7,8],4:[9,10,11],5:[12,13],6:[14,15,16]}
HOURS = {1:16,2:24,3:24,4:24,5:16,6:24}

EXTRA = {
1:{
"heading":"Recursión, descomposición y diseño de casos",
"paragraphs":[
"La recursión expresa una solución en términos de instancias más pequeñas del mismo problema. Para que sea correcta necesita uno o más casos base, una transformación que reduzca el tamaño y un argumento de que cada llamada se aproxima al caso base. Esta estructura aparece al recorrer árboles, dividir intervalos y explorar combinaciones. Una definición recursiva elegante no garantiza una implementación eficiente: repetir subproblemas puede multiplicar el trabajo y la profundidad puede agotar la pila de llamadas.",
"Descomponer un problema recursivamente exige identificar qué información debe devolverse. En una secuencia biológica, contar nucleótidos puede resolverse sobre un prefijo y el resto, pero esa formulación es menos eficiente que un recorrido iterativo en Python. En cambio, la estructura jerárquica de un árbol se ajusta naturalmente a funciones que procesan un nodo y llaman a sus hijos. La representación del dato debe influir en la estrategia y no solo la familiaridad del programador.",
"Los ejemplos mínimos sirven para descubrir la estructura. Antes de implementar conviene resolver manualmente entradas de tamaño cero, uno, dos y tres, registrar estados y buscar una regla general. Esta práctica revela empates, duplicados y decisiones no especificadas. Para algoritmos sobre datos biomédicos también deben probarse identificadores repetidos, registros incompletos y unidades incompatibles sin convertir el algoritmo en una regla clínica.",
"El diseño se completa con una matriz de casos que relaciona requisito, entrada, resultado esperado y propiedad examinada. Un mismo caso puede cubrir varias líneas de código pero no necesariamente varias condiciones conceptuales. La cobertura útil se obtiene desde la especificación: cada precondición, rama, frontera e invariante debe tener evidencia. Las pruebas no sustituyen el argumento de corrección, pero muestran si la implementación respeta el razonamiento declarado."],
"key_points":["Toda recursión necesita caso base, reducción y argumento de terminación.","La estructura de los datos condiciona si conviene iteración o recursión.","Las instancias mínimas revelan reglas y fronteras ocultas.","Los casos de prueba se derivan de requisitos e invariantes."],
"example":{"title":"Búsqueda recursiva de una ruta en una jerarquía","scenario":"Una ontología educativa se representa como un diccionario donde cada término contiene una lista de términos hijos. Se desea determinar si existe una ruta desde un concepto inicial hasta otro sin asumir que la jerarquía está libre de errores.","pseudocode":["Si el nodo actual es el objetivo, devolver la ruta.","Si el nodo ya fue visitado, detener esa rama.","Marcar el nodo y explorar cada hijo.","Si una llamada devuelve ruta, propagarla.","Si ninguna rama funciona, devolver ausencia."],"reasoning_steps":["El caso base reconoce el objetivo.","El conjunto visitados evita ciclos accidentales.","Cada llamada avanza a un nodo adyacente.","La ruta se construye sin modificar el grafo.","La ausencia se representa explícitamente."],"interpretation":"El algoritmo determina alcanzabilidad en la representación proporcionada; no valida la ontología ni la relación biológica entre conceptos.","limitations":["La primera ruta encontrada no es necesariamente la más corta.","La profundidad extrema puede requerir una versión iterativa.","La calidad depende de las relaciones de entrada."]},
"problems":[
{"prompt":"Especifica un algoritmo que cuente registros válidos y rechazados.","solution":"Define tipos y rangos, recorre una vez, mantiene dos contadores y comprueba que su suma coincida con el total."},
{"prompt":"Formula un invariante para calcular un máximo.","solution":"Tras procesar k elementos, maximo contiene el mayor de los primeros k valores aceptados."},
{"prompt":"Explica la terminación de búsqueda binaria.","solution":"El intervalo pendiente se reduce estrictamente en cada iteración y su longitud es un entero no negativo."},
{"prompt":"Diseña un caso adversarial para una búsqueda lineal.","solution":"Coloca el objetivo al final o ausente para forzar la inspección de todos los elementos."},
{"prompt":"Compara una solución iterativa y recursiva para sumar una lista.","solution":"Ambas son lineales; la iterativa usa memoria auxiliar constante y evita profundidad de pila."},
{"prompt":"Propón una propiedad de una función que elimina duplicados conservando orden.","solution":"La salida no contiene duplicados y su secuencia coincide con la primera aparición de cada elemento."},
{"prompt":"Distingue entrada inválida de resultado vacío.","solution":"Una entrada inválida incumple el contrato; un resultado vacío puede ser una salida válida para una consulta sin coincidencias."},
{"prompt":"Describe un oráculo para ordenar cinco valores.","solution":"Una secuencia manual conocida o la función estándar usada únicamente como referencia de prueba."}
],
"questions":[
{"question":"¿Qué tres condiciones hacen bien fundada una recursión?","answer":"Caso base, reducción hacia instancias menores y garantía de alcanzar el caso base."},
{"question":"¿Por qué un conjunto de visitados puede ser necesario en una jerarquía?","answer":"Porque los datos pueden contener ciclos y provocar repetición o recursión infinita."}
],
"sources":[{"title":"Recursion","organization":"MIT OpenCourseWare","url":"https://ocw.mit.edu/courses/6-006-introduction-to-algorithms-fall-2011/","type":"curso abierto"}]
},
2:{
"heading":"Complejidad experimental, memoria y límites del modelo",
"paragraphs":[
"La notación asintótica describe cómo crece un coste cuando aumenta el tamaño de entrada. No predice segundos exactos ni elimina constantes, arquitectura o lenguaje. O(g(n)) expresa una cota superior asintótica, Ω(g(n)) una inferior y Θ(g(n)) un crecimiento ajustado. Para usar estas categorías debe definirse n: número de registros, longitud de secuencia, nodos, aristas o píxeles. Cambiar esa definición cambia la interpretación.",
"El peor caso establece una garantía; el caso promedio necesita una distribución de entradas; el mejor caso rara vez basta para planificar recursos. Un diccionario puede ofrecer acceso promedio cercano a constante, pero colisiones y redimensionamientos importan. Un algoritmo lineal sobre millones de elementos puede ser aceptable, mientras uno cuadrático sobre la misma escala puede resultar prohibitivo. La relevancia depende también de cuántas veces se ejecuta y de la memoria disponible.",
"La complejidad espacial incluye datos auxiliares, pila recursiva, copias y estructuras temporales. En análisis biomédico, duplicar una matriz grande puede superar la memoria aunque el tiempo sea razonable. Procesar en streaming reduce memoria, pero limita operaciones que requieren acceso global. Debe diferenciarse memoria de entrada, memoria adicional y almacenamiento persistente.",
"Un benchmark contrasta hipótesis bajo condiciones controladas. Debe generar entradas reproducibles, ejecutar calentamiento, repetir mediciones, resumir mediana y dispersión y registrar hardware y versiones. Ajustar una recta en escala log-log puede sugerir un exponente, pero no demuestra por sí solo complejidad teórica. Rangos pequeños, caché, compilación y ruido pueden ocultar el comportamiento asintótico."],
"equations":[{"label":"Crecimiento lineal","latex":"T(n)=an+b\\in\\Theta(n)","interpretation":"El término lineal domina para n grande."},{"label":"Suma triangular","latex":"\\sum_{i=1}^{n} i=\\frac{n(n+1)}{2}\\in\\Theta(n^2)","interpretation":"Un bucle triangular realiza trabajo cuadrático."}],
"key_points":["La complejidad necesita una definición explícita del tamaño de entrada.","Peor caso, promedio y medición empírica responden preguntas distintas.","La memoria auxiliar puede limitar antes que el tiempo.","El benchmark contrasta, pero no sustituye, el análisis."],
"example":{"title":"Comparación de dos métodos para detectar duplicados","scenario":"Se comparan un doble bucle y un conjunto hash para detectar identificadores repetidos en registros sintéticos.","pseudocode":["Generar entradas reproducibles de tamaños crecientes.","Ejecutar ambos métodos sobre copias equivalentes.","Verificar que devuelvan el mismo resultado.","Repetir y registrar mediana temporal y memoria.","Representar tamaño frente a coste."],"reasoning_steps":["El doble bucle puede comparar pares y crecer cuadráticamente.","El conjunto recorre una vez con acceso promedio constante.","La equivalencia funcional se comprueba antes del rendimiento.","Las entradas incluyen duplicados tempranos, tardíos y ausencia.","La conclusión separa teoría y plataforma."],"interpretation":"Para tamaños grandes, el método hash debería escalar mejor en promedio, a cambio de memoria adicional.","limitations":["El peor caso del hashing depende de la implementación.","Los resultados temporales no se extrapolan a todo hardware.","Los identificadores sintéticos no representan todas las distribuciones reales."]},
"problems":[
{"prompt":"Deriva el coste de dos bucles de n iteraciones.","solution":"n·n operaciones dominantes, por tanto Θ(n²)."},{"prompt":"Analiza un bucle que divide n por dos.","solution":"Realiza aproximadamente log2(n) iteraciones, por tanto Θ(log n)."},{"prompt":"Distingue O(n) de Θ(n).","solution":"O(n) es cota superior; Θ(n) afirma cota superior e inferior del mismo orden."},{"prompt":"Explica por qué O(2n) se simplifica a O(n).","solution":"La constante 2 no cambia la clase de crecimiento asintótico."},{"prompt":"Compara copiar una lista y recorrerla in situ.","solution":"Ambas consumen tiempo lineal, pero la copia añade memoria Θ(n)."},{"prompt":"Propón un benchmark reproducible.","solution":"Fija semilla, genera tamaños definidos, repite, usa mediana y registra entorno."},{"prompt":"Explica una discrepancia entre teoría y medición pequeña.","solution":"Constantes, caché, asignación y ruido dominan antes del régimen asintótico."},{"prompt":"Analiza una matriz de adyacencia de n nodos.","solution":"Requiere Θ(n²) posiciones aunque existan pocas aristas."}
],
"questions":[{"question":"¿Qué información omite O grande?","answer":"Constantes, costes exactos, hardware y comportamiento para tamaños concretos."},{"question":"¿Por qué debe medirse memoria además de tiempo?","answer":"Porque copias y estructuras auxiliares pueden hacer inviable un algoritmo temporalmente aceptable."}],
"sources":[{"title":"Mathematics for Computer Science","organization":"MIT OpenCourseWare","url":"https://ocw.mit.edu/courses/6-042j-mathematics-for-computer-science-spring-2015/","type":"curso abierto"},{"title":"timeit — Measure execution time","organization":"Python Software Foundation","url":"https://docs.python.org/3/library/timeit.html","type":"documentación oficial"}]
},
3:{
"heading":"Interfaces, costes amortizados y semántica de las colecciones",
"paragraphs":[
"Una estructura de datos combina una representación con operaciones e invariantes. Dos estructuras pueden almacenar los mismos valores y ofrecer contratos diferentes. Un arreglo dinámico favorece acceso por índice y recorrido contiguo; una lista enlazada facilita ciertas inserciones cuando ya se dispone del nodo; una pila restringe el acceso al extremo superior; una cola conserva orden FIFO. La selección debe comenzar por operaciones dominantes y semántica.",
"El análisis amortizado distribuye operaciones ocasionalmente costosas entre muchas operaciones baratas. Añadir a una lista dinámica suele ser constante amortizado, aunque algunos append requieren reservar un bloque mayor y copiar referencias. Esta garantía no significa que cada llamada tenga el mismo coste. En flujos sensibles a latencia, las pausas individuales pueden importar además del promedio acumulado.",
"Las tablas hash implementan asociaciones y pertenencia mediante hash e igualdad. Las claves deben mantener ambos comportamientos durante su vida en la tabla. Las colisiones son inevitables y se resuelven internamente; el factor de carga influye en memoria y rendimiento. El acceso promedio eficiente no conserva automáticamente orden científico ni resuelve identificadores duplicados con significado distinto.",
"La representación debe preservar procedencia y multiplicidad. Convertir mediciones a conjunto elimina duplicados y puede destruir evidencia. Usar un diccionario por paciente puede sobrescribir visitas si la clave no incluye tiempo. En datos biomédicos conviene distinguir identidad de entidad, identidad de observación y posición temporal. Una estructura correcta computacionalmente puede ser semánticamente inadecuada."],
"key_points":["La interfaz y los invariantes definen la estructura, no solo su sintaxis.","El coste amortizado admite operaciones individuales costosas.","Hash e igualdad deben permanecer coherentes para las claves.","Orden, duplicados e identidad son propiedades científicas del dato."],
"example":{"title":"Índice de k-mers con tabla hash","scenario":"Se desea contar todas las subsecuencias de longitud k de una cadena de ADN educativa y consultar rápidamente sus frecuencias.","pseudocode":["Validar alfabeto y k positivo.","Crear diccionario vacío.","Recorrer posiciones desde 0 hasta longitud-k.","Extraer k-mer e incrementar su contador.","Devolver índice y número total de ventanas."],"reasoning_steps":["Hay n-k+1 ventanas si n≥k.","El diccionario conserva multiplicidades mediante conteos.","La consulta promedio evita recorrer toda la secuencia de nuevo.","La validación separa símbolos ambiguos según el contrato.","El total de conteos debe coincidir con las ventanas."],"interpretation":"El índice permite consultas exactas de patrones dentro de la secuencia proporcionada.","limitations":["No busca coincidencias con errores.","El número de claves puede crecer rápidamente.","No infiere función biológica de un patrón frecuente."]},
"problems":[
{"prompt":"Elige estructura para deshacer operaciones.","solution":"Una pila, porque se recupera primero la acción más reciente."},{"prompt":"Elige estructura para procesar eventos por llegada.","solution":"Una cola FIFO."},{"prompt":"Explica por qué un set no sirve para una serie temporal.","solution":"Elimina duplicados y no representa la secuencia de observación."},{"prompt":"Compara acceso en arreglo y lista enlazada.","solution":"El arreglo ofrece índice O(1); la lista enlazada requiere recorrer O(n)."},{"prompt":"Define una clave para varias visitas por paciente.","solution":"Una tupla inmutable como (paciente_id, fecha_visita)."},{"prompt":"Explica append amortizado.","solution":"La mayoría son constantes y las copias ocasionales se distribuyen entre muchas inserciones."},{"prompt":"Diseña una invariante para una cola circular.","solution":"El número de elementos coincide con la distancia modular entre frente y final bajo la convención elegida."},{"prompt":"Detecta un riesgo al sobrescribir diccionarios.","solution":"Claves no únicas pueden eliminar observaciones anteriores silenciosamente."}
],
"questions":[{"question":"¿Qué significa coste amortizado?","answer":"Coste promedio garantizado sobre una secuencia de operaciones, no sobre una sola operación aislada."},{"question":"¿Qué relación deben mantener __hash__ y __eq__?","answer":"Objetos iguales deben producir el mismo hash mientras sean claves."}],
"sources":[{"title":"Open Data Structures","organization":"Pat Morin","url":"https://opendatastructures.org/","type":"libro abierto"},{"title":"collections — Container datatypes","organization":"Python Software Foundation","url":"https://docs.python.org/3/library/collections.html","type":"documentación oficial"}]
},
4:{
"heading":"Representaciones de árboles y grafos, recorridos y prioridades",
"paragraphs":[
"Un árbol es un grafo conectado sin ciclos. Los árboles enraizados representan jerarquías mediante relaciones padre-hijo; los árboles de búsqueda ordenan claves para reducir el espacio de búsqueda; los montículos mantienen una relación parcial suficiente para recuperar prioridades. Estas estructuras no son intercambiables: un montículo encuentra el mínimo eficientemente, pero no mantiene todos los elementos ordenados.",
"La altura determina el coste de operaciones en árboles de búsqueda. Un árbol balanceado mantiene altura logarítmica, mientras inserciones ordenadas pueden producir una cadena de altura lineal. El balance requiere reglas y metadatos adicionales. En Python, muchas aplicaciones usan estructuras de biblioteca en lugar de implementar árboles balanceados, pero construir versiones educativas permite comprender invariantes y fallos.",
"Los grafos representan entidades y relaciones. Una lista de adyacencia usa memoria proporcional a nodos y aristas y es adecuada para redes dispersas; una matriz facilita consultar una arista pero consume espacio cuadrático. BFS explora por capas y obtiene caminos mínimos en grafos no ponderados. DFS profundiza y ayuda a detectar componentes, ciclos y órdenes de finalización.",
"Las colas de prioridad permiten procesar el elemento con menor o mayor prioridad. Un heap binario soporta inserción y extracción en tiempo logarítmico. La prioridad debe separar valor algorítmico de significado clínico: priorizar variantes por una puntuación educativa no convierte el ranking en evidencia de patogenicidad. Empates, estabilidad y procedencia deben declararse."],
"key_points":["Árbol de búsqueda, heap y jerarquía mantienen invariantes diferentes.","La altura controla el rendimiento de un árbol de búsqueda.","La representación del grafo depende de densidad y operaciones.","Una prioridad computacional no equivale a importancia clínica."],
"example":{"title":"Camino mínimo en una red de procesos","scenario":"Una red sintética conecta etapas de un pipeline y cada arista representa una transición permitida. Se desea obtener el menor número de pasos entre entrada y reporte.","pseudocode":["Inicializar cola con origen y distancia cero.","Marcar origen visitado.","Extraer un nodo y explorar vecinos no visitados.","Registrar predecesor y distancia.","Detener al encontrar destino y reconstruir ruta."],"reasoning_steps":["BFS procesa nodos por distancia creciente.","Marcar al encolar evita duplicados.","Los predecesores permiten reconstruir la ruta.","La garantía supone aristas sin peso o igual peso.","La ausencia de ruta se comunica explícitamente."],"interpretation":"La ruta minimiza número de transiciones en el modelo de red utilizado.","limitations":["No minimiza tiempo si las transiciones tienen duraciones distintas.","No valida que el pipeline sea científicamente adecuado.","Los nodos y aristas dependen del esquema de entrada."]},
"problems":[
{"prompt":"Da los recorridos de un árbol pequeño en preorden e inorden.","solution":"Preorden visita raíz-izquierda-derecha; inorden izquierda-raíz-derecha."},{"prompt":"Explica el peor caso de un BST no balanceado.","solution":"Puede degenerar en cadena y hacer búsqueda e inserción O(n)."},{"prompt":"Selecciona representación para red dispersa.","solution":"Lista de adyacencia, con espacio Θ(V+E)."},{"prompt":"Selecciona BFS o DFS para camino mínimo sin pesos.","solution":"BFS."},{"prompt":"Usa DFS para detectar ciclo dirigido.","solution":"Mantén estados no visitado, en exploración y finalizado; una arista a en exploración indica ciclo."},{"prompt":"Explica la operación principal de heapq.","solution":"Mantiene el mínimo en la raíz y permite push/pop logarítmicos."},{"prompt":"Distingue árbol de decisión y árbol de búsqueda.","solution":"El primero representa decisiones; el segundo organiza claves por orden."},{"prompt":"Analiza matriz de adyacencia.","solution":"Consulta de arista O(1), memoria Θ(V²) y recorrido de vecinos O(V)."}
],
"questions":[{"question":"¿Qué garantiza BFS en un grafo no ponderado?","answer":"Encuentra distancias mínimas en número de aristas desde el origen."},{"question":"¿Por qué un heap no es una lista ordenada?","answer":"Solo garantiza la relación de prioridad entre padres e hijos, no un orden total."}],
"sources":[{"title":"NetworkX Documentation","organization":"NetworkX Developers","url":"https://networkx.org/documentation/stable/","type":"documentación oficial"},{"title":"heapq — Heap queue algorithm","organization":"Python Software Foundation","url":"https://docs.python.org/3/library/heapq.html","type":"documentación oficial"}]
},
5:{
"heading":"Estabilidad, selección y búsqueda sobre datos estructurados",
"paragraphs":[
"Ordenar transforma una colección según una clave y un criterio. La estabilidad conserva el orden relativo de elementos con claves iguales y permite ordenar por varios campos de manera reproducible. Un algoritmo in-place reduce memoria auxiliar, pero puede destruir el orden original. La elección depende de tamaño, distribución, necesidad de estabilidad, memoria, acceso y coste de comparar claves.",
"Insertion sort es eficiente para colecciones pequeñas o casi ordenadas; merge sort garantiza tiempo n log n y estabilidad con memoria adicional; quicksort suele ser rápido, pero su peor caso es cuadrático según pivote y partición; Timsort explota tramos ya ordenados y es usado por Python. Memorizar nombres sin analizar propiedades produce decisiones frágiles.",
"La búsqueda lineal no necesita orden y puede detenerse temprano; la binaria reduce el intervalo a la mitad, pero exige orden consistente y acceso adecuado. Mantener un índice tiene coste de construcción y actualización. Para consultas repetidas puede compensar; para una sola consulta sobre datos pequeños, ordenar previamente puede costar más que recorrer.",
"Seleccionar top-k no siempre requiere ordenar todo. Un heap de tamaño k conserva candidatos con coste aproximado n log k. Las decisiones sobre empates y valores faltantes deben ser explícitas. En variantes genómicas sintéticas, una puntuación numérica puede ordenar registros, pero el ranking depende del modelo de puntuación y no demuestra relevancia biológica o clínica."],
"equations":[{"label":"Búsqueda binaria","latex":"T(n)=T(n/2)+\\Theta(1)=\\Theta(\\log n)","interpretation":"Cada paso reduce el intervalo aproximadamente a la mitad."},{"label":"Ordenamiento por comparación","latex":"\\Omega(n\\log n)","interpretation":"Cota inferior general para ordenamientos por comparación en el modelo estándar."}],
"key_points":["La estabilidad es una propiedad semántica del ordenamiento.","No existe un algoritmo universalmente mejor para toda entrada.","La búsqueda binaria exige orden y criterio coherente.","Top-k puede resolverse sin ordenar toda la colección."],
"example":{"title":"Ordenamiento estable de observaciones","scenario":"Registros sintéticos contienen participante, tiempo y valor. Se desea ordenar por participante y luego por tiempo conservando el orden de captura para empates exactos.","pseudocode":["Validar campos obligatorios.","Conservar posición original.","Ordenar establemente por clave compuesta participante-tiempo.","Comprobar que no cambió el multiconjunto de registros.","Verificar monotonía de la clave."],"reasoning_steps":["La clave compuesta define el orden total esperado.","La estabilidad conserva empates según captura.","La propiedad de permutación evita pérdidas o duplicados.","La monotonía comprueba el resultado.","La posición original permite auditoría."],"interpretation":"La salida queda preparada para recorridos temporales por participante.","limitations":["Ordenar no corrige tiempos erróneos.","La dependencia temporal requiere análisis adicional.","Los identificadores deben estar normalizados previamente."]},
"problems":[
{"prompt":"Compara insertion sort y merge sort en datos casi ordenados.","solution":"Insertion puede acercarse a lineal; merge mantiene n log n y usa memoria adicional."},{"prompt":"Explica estabilidad con dos claves.","solution":"Permite ordenar primero por clave secundaria y luego por primaria sin perder el orden secundario en empates."},{"prompt":"Justifica búsqueda lineal para una consulta única.","solution":"Evita el coste previo de ordenar o construir un índice."},{"prompt":"Deriva iteraciones de búsqueda binaria en 1024 elementos.","solution":"Como 1024=2^10, requiere alrededor de 10 divisiones."},{"prompt":"Diseña una prueba de permutación.","solution":"Compara conteos de cada elemento antes y después del ordenamiento."},{"prompt":"Selecciona top 20 entre un millón.","solution":"Mantén un min-heap de tamaño 20 para coste O(n log 20)."},{"prompt":"Explica un empate reproducible.","solution":"Define una clave secundaria estable como identificador o posición original."},{"prompt":"Describe cuándo quicksort puede degradarse.","solution":"Particiones muy desequilibradas repetidas producen profundidad y trabajo cuadráticos."}
],
"questions":[{"question":"¿Qué conserva un ordenamiento estable?","answer":"El orden relativo de elementos con claves iguales."},{"question":"¿Cuándo compensa construir un índice?","answer":"Cuando el coste se amortiza mediante muchas consultas o necesidades de acceso repetido."}],
"sources":[{"title":"Sorting HOW TO","organization":"Python Software Foundation","url":"https://docs.python.org/3/howto/sorting.html","type":"documentación oficial"},{"title":"bisect — Array bisection algorithm","organization":"Python Software Foundation","url":"https://docs.python.org/3/library/bisect.html","type":"documentación oficial"}]
},
6:{
"heading":"Estrategias de diseño, optimización y validación reproducible",
"paragraphs":[
"El diseño algorítmico dispone de patrones. Fuerza bruta enumera posibilidades y ofrece una referencia clara; divide y vencerás separa subproblemas y combina resultados; greedy toma decisiones locales que necesitan una propiedad para ser globalmente correctas; programación dinámica reutiliza subproblemas solapados. Elegir un patrón exige demostrar sus condiciones, no solo reconocer una apariencia.",
"Optimizar comienza con un perfil. Debe localizarse el cuello de botella y definir una métrica relevante. Cambiar estructura, evitar recomputación o reducir copias suele aportar más que microoptimizaciones. Cada modificación se compara con una implementación de referencia mediante pruebas de regresión. Un resultado más rápido que cambia silenciosamente empates, precisión o registros no es una mejora válida.",
"Las pruebas basadas en propiedades generan múltiples entradas y comprueban invariantes: ordenar conserva elementos, BFS asigna distancias no decrecientes, un heap siempre extrae prioridades ordenadas. Las pruebas metamórficas relacionan ejecuciones cuando no existe un oráculo simple. Añadir un nodo aislado a un grafo no debe cambiar caminos entre nodos existentes, por ejemplo.",
"La reproducibilidad integra código, datos, entorno, semillas, comandos, perfiles y documentación. Un proyecto biomédico debe declarar finalidad educativa, procedencia y límites. El rendimiento no demuestra validez científica; la correctitud no demuestra seguridad clínica; una métrica favorable no demuestra utilidad. La entrega final debe permitir reconstruir resultados y también comprender qué no puede concluirse."],
"key_points":["Cada estrategia de diseño requiere condiciones de corrección.","Optimizar exige medir y conservar una referencia correcta.","Las propiedades y relaciones metamórficas amplían los oráculos.","Correctitud, rendimiento, validez científica y utilidad clínica son niveles distintos."],
"example":{"title":"Selección greedy de intervalos no solapados","scenario":"Se dispone de intervalos sintéticos de eventos y se desea seleccionar el máximo número de intervalos compatibles.","pseudocode":["Ordenar por tiempo de finalización.","Seleccionar el primer intervalo.","Recorrer y aceptar cada intervalo cuyo inicio sea posterior o igual al final seleccionado.","Devolver selección y comprobar no solapamiento."],"reasoning_steps":["La elección local termina antes y deja mayor espacio restante.","El argumento de intercambio justifica que existe una solución óptima con esa primera elección.","Ordenar domina el coste con O(n log n).","La verificación comprueba compatibilidad y pertenencia.","Una fuerza bruta pequeña sirve como oráculo."],"interpretation":"El algoritmo maximiza cantidad bajo el modelo de intervalos y compatibilidad declarado.","limitations":["No maximiza duración ni valor ponderado.","Los tiempos deben estar en una escala coherente.","No interpreta prioridad clínica de eventos."]},
"problems":[
{"prompt":"Compara fuerza bruta y programación dinámica para Fibonacci.","solution":"La recursión ingenua repite subproblemas exponencialmente; memoización reduce a tiempo lineal."},{"prompt":"Da un contraejemplo a una estrategia greedy sin justificar.","solution":"Elegir siempre la moneda mayor puede fallar en sistemas de monedas no canónicos."},{"prompt":"Diseña una prueba metamórfica para ordenar.","solution":"Ordenar una permutación de la misma entrada debe producir la misma secuencia ordenada."},{"prompt":"Explica qué debe conservar una optimización.","solution":"Contrato, resultados dentro de tolerancia, errores, orden relevante y trazabilidad."},{"prompt":"Propón un perfil para un índice de k-mers.","solution":"Mide extracción, hashing y memoria por tamaños y valores de k reproducibles."},{"prompt":"Distingue prueba unitaria e integración.","solution":"La unitaria aísla componentes; integración comprueba su interacción."},{"prompt":"Define una prueba de regresión.","solution":"Conserva una entrada que antes falló y exige el resultado corregido."},{"prompt":"Explica por qué CI no valida clínicamente.","solution":"Solo ejecuta comprobaciones codificadas y no establece seguridad, eficacia ni utilidad asistencial."}
],
"questions":[{"question":"¿Qué justifica una estrategia greedy?","answer":"Una propiedad demostrable, frecuentemente mediante argumento de intercambio o estructura óptima."},{"question":"¿Qué diferencia existe entre perfil y benchmark?","answer":"El perfil localiza dónde se consume recursos; el benchmark compara rendimiento bajo un protocolo controlado."}],
"sources":[{"title":"The Turing Way — Reproducible Research","organization":"The Turing Way Community","url":"https://book.the-turing-way.org/reproducible-research/reproducible-research","type":"guía abierta"},{"title":"Hypothesis Documentation","organization":"HypothesisWorks","url":"https://hypothesis.readthedocs.io/","type":"documentación oficial"}]
}
}

for unit_no in range(1,7):
    path = UNIT_DIR / f"unit-{unit_no:02d}.json"
    data = json.loads(path.read_text(encoding="utf-8"))
    extra = EXTRA[unit_no]
    data["schema_version"] = "2.0"
    data["status"] = "review"
    data["estimated_hours"] = HOURS[unit_no]
    data["weeks"] = WEEKS[unit_no]
    data["difficulty"] = "Fundamental" if unit_no <= 2 else "Intermedia"
    data["prerequisite_knowledge"] = ["Fundamentos de Programación en Python.","Funciones, colecciones, archivos y pruebas básicas.","Álgebra elemental, sumatorias y logaritmos introductorios."]
    data["progression"] = {"previous":"Unidad anterior o Fundamentos de Programación.","next":"La siguiente familia de estructuras y estrategias del curso."}
    data["theory_sections"].append({k:extra[k] for k in ("heading","paragraphs","key_points")})
    if "equations" in extra:
        data["theory_sections"][-1]["equations"] = extra["equations"]
    original = data.pop("worked_example")
    data["worked_examples"] = [original, extra["example"]]
    activity = data.pop("guided_activity")
    data["guided_activities"] = [activity]
    data["practice_sets"] = [{"title":"Práctica acumulativa de la unidad","purpose":"Consolidar especificación, implementación, análisis y crítica.","problems":extra["problems"]}]
    data["self_assessment"].extend(extra["questions"])
    for source in extra["sources"]:
        if source["url"] not in {s["url"] for s in data["sources"]}:
            data["sources"].append(source)
    data["editorial_notice"] = "Material educativo generado y revisado automáticamente; requiere revisión docente experta. No equivale a acreditación universitaria, software médico validado ni recomendación clínica."
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2)+"\n", encoding="utf-8")

print("Migración semestral de Algoritmos y Estructuras de Datos aplicada.")
